### ISSUE TITLE
Cannot confirm the trades

### ISSUE THREAD

**Issue by cromwell221** [hyt47/SteamDesktopAuthenticator-Mod-47#12]
Hello. I cannot confirm any Trades or Listing since yesterday. No changes to system were made.
It started to give an error instead of the confirmation pop-up. Smth like that: System.ArgumentOutOfRangeException
I guess it's Framework 4 related. I am using mini for XP release. Tried on another PC - same result.
Can you check that please?

**Comment by jackqc** [comment]
Hi. I'm having the same problem (also using mini for XP). I suppose it's related to the new feature to confirm multiple market listings in one checkbox. It's still working with trades and it's working with the original Steam Desktop Authenticator, which I'm using on Win7. Here's the full debug output:
"Unhandled exeption has occured in your apllication. [...] Specified argument was out of the range of valid values: Parameter name: i."

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
   at System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__0(Object state)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 (RTMGDR.030319-2300)

##     CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Steam Desktop Authenticator 47
    Assembly Version: 1.0.5.5
    Win32 Version: 1.0.5.5

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/Steam%20Desktop%20Authenticator%2047.exe

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/Newtonsoft.Json.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

SteamAuth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/SteamAuth.DLL

System.Threading.Tasks
    Assembly Version: 2.6.8.0
    Win32 Version: 2.6.8.0

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/System.Threading.Tasks.DLL

Microsoft.Threading.Tasks
    Assembly Version: 1.0.12.0
    Win32 Version: 1.0.168.0

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/Microsoft.Threading.Tasks.DLL

Microsoft.Threading.Tasks.Extensions.Desktop
    Assembly Version: 1.0.168.0
    Win32 Version: 1.0.168.0

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/Microsoft.Threading.Tasks.Extensions.Desktop.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Runtime
    Assembly Version: 2.6.8.0
    Win32 Version: 2.6.8.0

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/System.Runtime.DLL

Microsoft.Threading.Tasks.Extensions
    Assembly Version: 1.0.12.0
    Win32 Version: 1.0.168.0

##     CodeBase: file:///C:/Documents%20and%20Settings/root/Desktop/SDA%2047%20Mini%20for%20XP%20Release/Microsoft.Threading.Tasks.Extensions.DLL

System.Net
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.dll

System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Jacob31oo** [comment]
Same problem here. Mini for XP version crashing if checks for market listings. Win 7 version updated about 10h ago and works fine.

**Comment by hyt47** [comment]
Hi. Sorry I was working on another project and I didn't check my messages. I finished compiling [v1.0.7.2](https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/releases/tag/1.0.7.2).

 Tomorrow I will compile for XP. Enjoy ^_^

**Comment by hyt47** [comment]
I finished compiling for XP. Enjoy ^_^

**Comment by cromwell221** [comment]
Thank you a lot! Just tried and it works well.
But now I have no pop-up windows with confirmations. I can confirm from View Confirmations List button though. Tried to restart the app, force refresh session.

**Comment by hyt47** [comment]
You have multiple accounts added ? I checked using a few  steam accounts and I see that for me the popup shows only if the account is selected in the list. I will fix that tomorrow!

**Comment by cromwell221** [comment]
No, I have single acc there

**Comment by hyt47** [comment]
Fixed! Thx for info!

**Comment by cromwell221** [comment]
Hello.Confirmation of the trades not working again. No pop-up window

**Comment by hyt47** [comment]
Hi! Is still not working ? I'll run a few tests...
