### ISSUE TITLE
Check all accounts for confirmations problem

### ISSUE THREAD

**Issue by ghost** [hyt47/SteamDesktopAuthenticator-Mod-47#14]
http://imgur.com/a/qIRd6

1.Red square When i ticked check all accounts for confirmations it still check for same accounts for 3 times (I have 3 accounts in SDA47)

2.Yellow square, On the title of View confirmation it still show "Trade confirmation". it must be "Confirmation"

thanks ;)

**Comment by hyt47** [comment]
Hi!
You are using v1.0.7.4?

v1.0.7.3 had this problem,
In v1.0.7.4 if the option from settings `Check all accounts for confirmations` is not `on` and is not saved, the app will check for confirmations ony the account that is selected in the list.

I tested again v1.0.7.4 and it seems to work fine.

If you still have this problem try and do a clean install again.
- keep your old SDA 47 app intact,
- Exit Old app
- download  v1.0.7.4
- extract-it
- copy your maFolder to this app folder
- after that open the maFolder and delete manifest.json to reset your settings
- if your accounts are encrypted or decrypted, because you are using SDA 47, it's safe to delete the manifest.json
- open the New App
- if you see all your accounts in the list you can delete the old app

If u get this error again tell me, I will run multiple tests to see if I encounter this problem.

**Comment by ghost** [comment]
thanks for the help @hyt47 i just clean install and can do this!
